# FAILURE GENERATOR
quarkus.langchain4j.ollama.demo-generator.chat-model.model-id=gpt-oss:120b-cloud
quarkus.langchain4j.ollama.demo-generator.timeout=120s
quarkus.langchain4j.ollama.demo-generator.chat-model.temperature=0.8

# ANALYZER
quarkus.langchain4j.ollama.demo-analyzer.chat-model.model-id=gpt-oss:120b-cloud
quarkus.langchain4j.ollama.demo-analyzer.timeout=120s
quarkus.langchain4j.ollama.demo-analyzer.chat-model.temperature=0.0

quarkus.langchain4j.timeout=2m

# Configuração de Log
quarkus.log.console.format=%d{HH:mm:ss} %-5p [%c{2.}] (%t) %s%e%n